INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 0, 'PIF-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 2, 'PIF-SYMBOL');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 5, 'PIF-POLICY-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 12, 'PIF-MODULE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 14, 'PIF-MASTER-CO-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 16, 'PIF-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 18, 'PIF-AMEND-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 20, 'PIF-EFFECTIVE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 28, 'PIF-EXPIRATION-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 36, 'PIF-INSTALLMENT-TERM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 39, 'PIF-NUMBER-INSTALLMENTS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 41, 'PIF-RISK-STATE-PROV');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 43, 'PIF-COMPANY-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 45, 'PIF-BRANCH');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 47, 'PIF-PROFIT-CENTER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 50, 'PIF-AGENCY-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 57, 'PIF-ENTERED-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 65, 'PIF-TOTAL-AGEN-PREM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 77, 'PIF-LINE-BUSINESS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 80, 'PIF-ISSUE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 81, 'PIF-COMPANY-LINE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 82, 'PIF-PAY-SERVICE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 83, 'PIF-MODE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 84, 'PIF-AUDIT-CODE  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 85, 'PIF-KIND-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 86, 'PIF-VARIATION-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 87, 'PIF-SORT-NAME ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 91, 'PIF-PRODUCER-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 93, 'PIF-REVIEW-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 94, 'PIF-MVR-REPORT-YEAR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 95, 'PIF-RISK-GRADE-GUIDE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 96, 'PIF-RISK-GRADE-UNDWR ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 97, 'PIF-RENEWAL-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 98, 'PIF-REASON-AMENDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 101, 'PIF-RENEW-PAY-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 102, 'PIF-RENEW-MODE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 103, 'PIF-RENEW-POLICY-SYMBOL');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 106, 'PIF-RENEW-POLICY-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 113, 'PIF-ORIGINAL-INCEPT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 119, 'PIF-CUSTOMER-NUMBER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 129, 'PIF-SPECIAL-USE-A ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 133, 'PIF-SPECIAL-USE-B ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 140, 'PIF-ZIP-POSTAL-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 146, 'PIF-ADDRESS-LINE-1 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 176, 'PIF-ADDRESS-LINE-2');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 206, 'PIF-ADDRESS-LINE-3 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 236, 'PIF-ADDRESS-LINE-4  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 266, 'PIF-HISTORY-OPTION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 267, 'PIF-FINAL-AUDIT-IND ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 269, 'PIF-EXCESS-CLAIM-IND  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 270, 'PIF-REST-OF-ZIP-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 0, 'COMMENTS-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 2, 'COMMENTS-REASON-SUSPENDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 4, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 5, 'COMMENTS-DEST ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 10, 'COMMENTS-REQUESTED-BY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 13, 'COMMENTS-SUSPENSE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 21, 'COMMENTS-SEQ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 23, 'COMMENTS-AREA ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 0, 'DESCRIPTION-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 2, 'USE-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 4, 'UNIT-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 7, 'DESCRIPTION-SEQUENCE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 8, 'DESCRIPTION-SORT-NAME');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 12, 'DESCRIPTION-ZIP-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 18, 'DESCRIPTION-LINE-1 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 48, 'DESCRIPTION-LINE-2 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 78, 'DESCRIPTION-LINE-3 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 108, 'DESCRIPTION-LINE-4');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 0, 'FRR-RECORD-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 2, 'FRR-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 4, 'FRR-AMENDMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 5, 'FRR-LAST-CHANGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 13, 'FRR-LOCATION-STATE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 15, 'FRR-TERRITORY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 17, 'FRR-FORM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 18, 'FRR-NUMBER-OF-FAMILIES ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 20, 'FRR-OCCUPANCY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 21, 'FRR-CONSTRUCTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 22, 'FRR-PROTECTION-CLASS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 24, 'FRR-DEDUCTIBLE-TYPE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 25, 'FRR-DEDUCTIBLE-AMOUNT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 29, 'FRR-HYDRANT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 33, 'FRR-FIRE-STATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 34, 'FRR-INSIDE-CITY   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 36, 'FRR-BUILDING-AMOUNT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 43, 'FRR-BUILDING-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 51, 'FRR-CONTENTS-AMOUNT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 58, 'FRR-CONTENTS-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 66, 'FRR-EC-AEC-COVERAGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 67, 'FRR-VANDALISM-MALICIOUS-MIS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 68, 'FRR-NUMBER-OF-STORIES ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 69, 'FRR-INFLATION-GUARD ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 71, 'FRR-VALUE-UP ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 72, 'FRR-MONEY-ENDORSEMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 75, 'FRR-YEAR-OF-CONSTRUCTION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 79, 'FRR-AGENTS-COMMISSION   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 82, 'FRR-ZIP-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 87, 'FRR-ORIGINAL-RATE-BOOK');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 88, 'FRR-COUNTY-TAX-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 91, 'FRR-CITY-TAX-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 94, 'FRR-CURR-REPLACEMENT-COST ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 100, 'FRR-CURR-REPLACE-COST-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 106, 'FRR-REPLACEMENT-COST ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 112, 'FRR-INSPECTION-YEAR  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 116, 'FRR-LAST-VALUE-CHANGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 117, 'FRR-INSPECTION-REPORT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 118, 'FRR-REPLACE-COST-METHOD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 119, 'FRR-HISTORY-OPTION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 120, 'FRR-NEW-PREMIUM   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 129, 'FRR-OLD-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 138, 'FRR-WINDSTORM-ASSUMPTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 139, 'FRR-COMMERCIAL-INDICATOR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 140, 'FRR-RATE-BOOK ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 141, 'FRR-LAST-CHANGE-FACTOR   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 144, 'FRR-PERSONAL-LIABILITY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 145, 'FRR-MEDICAL-PAYMENTS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 146, 'FRR-BODILY-INJURY  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 147, 'FRR-PROPERTY-DAMAGE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 148, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 150, 'XTEND-COVERAGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 151, 'WIND_CONSTRUCT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 152, 'COINS-PCT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 0, 'PCTL-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 2, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 3, 'PCTL-LOC');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 5, 'PCTL-FORM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 12, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 14, 'PCTL-SEQ-01');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 16, 'PCTL-SEQ-02');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 18, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 20, 'PCTL-DATA-01');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 60, 'PCTL-DATA-02');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 100, 'PCTL-DATA-03');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 140, 'PCTL-DATA-04');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 180, 'PCTL-DATA-05');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 0, 'FIRE-PREMIUM-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 2, 'FIRE-PREMIUM-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 3, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 4, 'FIRE-TOTAL-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 13, 'FIRE-PREMIUM-FORMS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 16, 'FIRE-PREMIUM-SEGMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 18, 'FIRE-COVERAGE-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 0, 'HRR-RECORD-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 2, 'HRR-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 3, 'HRR-AMENDMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 4, 'HRR-LAST-CHANGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 12, 'HRR-LOCATION-STATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 14, 'HRR-TERRITORY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 16, 'HRR-FORM  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 17, 'HRR-NUMBER-OF-FAMILIES ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 18, 'HRR-CONSTRUCTION  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 19, 'HRR-PROTECTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 21, 'HRR-DEDUCTIBLE-TYPE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 22, 'HRR-DEDUCTIBLE-AMOUNT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 26, 'HRR-COVERAGE-A-LIMIT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 32, 'HRR-COVERAGE-A-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 40, 'HRR-COVERAGE-B-LIMIT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 45, 'HRR-COVERAGE-C-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 51, 'HRR-COVERAGE-C-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 59, 'HRR-COVERAGE-D-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 64, 'HRR-COVERAGE-D-PREMIUM  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 72, 'HRR-COVERAGE-E-LIMIT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 79, 'HRR-COVERAGE-F-LIMIT  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 84, 'HRR-COVERAGE-E-F-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 92, 'HRR-APPROVED-ROOF ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 93, 'HRR-HYDRANT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 97, 'HRR-INSIDE-CITY  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 99, 'HRR-AUTOMATIC-VALUE-UP');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 100, 'HRR-NO-OF-APARTMENTS  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 102, 'HRR-LIABILITY-ZONE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 104, 'HRR-MONEY-ENDORSEMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 107, 'HRR-FIRE-EC-RATE  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 112, 'HRR-WIND-HAIL-EXCLUSION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 113, 'HRR-THEFT-EXTENSION  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 114, 'HRR-INFLATION-GUARD  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 116, 'HRR-THEFT-250-DEDUCTIBLE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 117, 'HRR-CLASS-RATED ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 118, 'HRR-YEAR-OF-CONSTRUCTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 122, 'HRR-ZIP-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 127, 'HRR-ORIG-ENDRSE-RT-BOOK');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 128, 'HRR-COUNTY-LOCATION  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 131, 'HRR-CITY-LOCATION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 134, 'HRR-CURR-REPLACEMENT-COST');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 137, 'HRR-CONTINGENT-LIABILITY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 138, 'HRR-SPECIAL-LOSS-PCT  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 141, 'HRR-CURR-REPLACE-COST-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 147, 'HRR-REPLACEMENT-COST ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 150, 'SECONDARY-RESIDENCE-USE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 151, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 152, 'HRR-HIGH-ORDER-COVD-DIGIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 153, 'HRR-INSPECTION-YEAR ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 157, 'HRR-LAST-VALUE-CHANGE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 158, 'HRR-INSPECTION-REPORT  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 159, 'HRR-REPLACE-COST-METHOD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 160, 'HRR-AGENT-COMMISSION  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 163, 'HRR-HISTORY-OPTION   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 164, 'HRR-NEW-PREMIUM   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 173, 'HRR-OLD-PREMIUM   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 182, 'HRR-PREMIUM-GROUP');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 185, 'HRR-ORIGINAL-RATE-BOOK ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 186, 'HRR-LAST-CHANGE-FACTOR ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 0, 'HOMEOWNERS-PREM-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 2, 'HOMEOWNERS-PREM-SEQ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 3, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 4, 'HOMEOWNERS-BASE-PREM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 13, 'HOMEOWNERS-PREM-FORM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 16, 'HOMEOWNERS-PREM-SEG');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 17, 'HOMEOWNERS-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 0, 'DRIVER-KEY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 2, 'DRIVER-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 4, 'DRIVER-NAME');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 26, 'DRIVER-LICENSE-NBR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 45, 'DRIVER-DATE-BIRTH');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 53, 'DRIVER-LICENSE-STATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 55, 'DRIVER-SEX');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 56, 'DRIVER-MARITAL-STAT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 57, 'DRIVER-RLTN-TO-INDS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 58, 'DRIVER-PRIN-OPRTR (1)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 59, 'DRIVER-PRIN-OPRTR (2)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 60, 'DRIVER-PRIN-OPRTR (3)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 61, ' DRIVER-PT-OPRTR (1)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 62, ' DRIVER-PT-OPRTR (2)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 63, ' DRIVER-PT-OPRTR (3)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 64, 'DRIVER-AGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 66, 'DRIVER-SPECIAL-USE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 72, 'DRIVER-CF-ATTRIBUTE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 73, 'ATTRIBUTE-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 76, 'ATTRIBUTE-VALUE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 77, 'ATTRIBUTE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 0, 'PER-ID ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 2, 'PER-USE-CD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 3, 'PER-USE-DATA');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 6, 'PER-USE-SEQUENCE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 7, 'PER-AMENDMENT-NBR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 8, 'PER-ENTERED-DATE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 16, 'PER-DESC-LINE-1');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 96, 'PER-DESC-LINE-2 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 166, 'PER-DESC-LINE-3 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 226, 'HISTORY-STATUS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 227, 'ORIGINAL-RATEBOOK');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 228, 'CURRENT-RATEBOOK');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 0, 'VCR-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 2, 'VCR-UNIT-NUMBER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 5, 'VCR-SEGMENT-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 6, 'VCR-AMEND-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 7, 'VCR-CHANGE-EFFECT-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 15, 'VEHICLE-REASON-AMENDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 18, 'VEHICLE-TOTAL-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 27, 'VEHICLE-OLD-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 36, 'VCR-COVERAGE-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 38, 'VCR-COVERAGE-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 45, 'VCR-COVERAGE-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 54, 'VCR-CVRG-RATE-BOOK-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 0, 'FORMS-ID ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 2, 'FORMS-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 5, 'FORM-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 12, 'FORM-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 16, 'FORM-ACTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 0, 'REIN-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 2, 'REINS-SECTION-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 3, 'REINS-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 6, 'REINS-LAYER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 7, 'REINS-COMPANY-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 11, 'REINS-EFFECTIVE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 19, 'REINS-PCT-PREM-CEDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 26, 'REINS-PCT-LOSS-CEDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 33, 'REINS-PCT-FAC-COMM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 38, 'REINS-EXPRTION-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 46, 'REINS-CESSION-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 56, 'REINS-TYPE  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 57, 'REINS-ENTERED-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 65, 'REINS-BROKER-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 69, 'REINS-EXCESS-AMT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 78, 'REINS-OCCUR-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 87, 'REINS-AGGR-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 96, 'REINS-SPECIAL-USE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 0, 'LOSS-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 2, 'LOSS-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 5, 'LOSS-MAJOR-PERIL');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 8, 'LOSS-MAJOR-PERIL-SEQ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 10, 'LOSS-COV-EFF-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 18, 'LOSS-PART    ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 19, 'LOSS-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 27, 'LOSS-OCCURENCE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 29, 'LOSS-CLAIMANT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 31, 'LOSS-TRANSACTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 33, 'LOSS-REINS-CO-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 37, 'LOSS-DATE-REPORTED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 45, 'LOSS-CAUSE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 47, 'LOSS-CATASTROPHE-NO ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 49, 'LOSS-XCSS-CATASTROPHE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 54, 'LOSS-ADJUSTOR-NO ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 57, 'LOSS-EXAMINER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 59, 'LOSS-PAID-OR-RESV-AMT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 70, 'LOSS-EXPENSE-AMT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 79, 'LOSS-BANK-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 81, 'LOSS-DRAFT-NO ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 86, 'LOSS-DATE-OF-DRAFT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 94, 'LOSS-DRAFT-PAY-TO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 97, 'LOSS-DRAFT-MAIL-TO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 98, 'LOSS-ORIGINAL-RESERVE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 106, 'LOSS-ACCT-ENTERED-DT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 112, 'LOSS-CLAIMANT-NAME');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 142, 'LOSS-PLANT-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 146, 'LOSS-ACCIDENT-STATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 148, 'LOSS-AVG-RESERVE-CD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 149, 'LOSS-BRANCH');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 152, 'LOSS-IND-DRAFT-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 160, 'LOSS-WEEKLY-WAGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 166, 'LOSS-PAYMENT-RATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 172, 'LOSS-FREQUENCY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 173, 'LOSS-PERIOD-PAY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 176, 'LOSS-CYCLE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 177, 'LOSS-AGE  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 179, 'LOSS-TIME-EMP-YEARS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 181, 'LOSS-TIME-EMP-MTHS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 183, 'LOSS-DISABILITY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 185, 'LOSS-INDUSTRIAL-COMM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 195, 'LOSS-CESSION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 205, 'LOSS-AIA-CODES');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 211, 'LOSS-ACCIDENT-DESC');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 241, 'LOSS-NET-CHG-OFFSET');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 245, 'LOSS-NEXT-REVIEW-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 253, 'LOSS-1099-NUMBER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 263, 'LOSS-CLAIM-PAYEE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 266, 'LOSS-NOTES-DRFT-PAYEE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 284, 'LOSS-CONVERSION-NBR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 296, 'LOSS-SPECIAL-USE-1');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 304, 'LOSS-SPECIAL-USE-2');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 307, 'LOSS-SUIT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 308, 'LOSS-EXCESS-STATUS-IND');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 309, 'LOSS-TIME');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 313, 'LOSS-DAY-NR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 0, 'ARR-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 2, 'ARR-BASE-BILLING-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 10, 'ARR-DUE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 18, 'ARR-ACCT-TRANS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 20, 'ARR-RCPT-TRANS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 22, 'ARR-AMT-DUE-RCVD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 33, 'ARR-NOTICE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 34, 'ARR-DATE-LAST-NOTICE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 42, 'ARR-CARRY-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 50, 'ARR-DATE-OF-DEPOSIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 58, 'ARR-RCPT-COMM-RATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 61, 'ARR-BANK-NUMBER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 63, 'ARR-PRIOR-AMT-BILL');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 0, 'PIF-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 2, 'PIF-SYMBOL');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 5, 'PIF-POLICY-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 12, 'PIF-MODULE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 14, 'PIF-MASTER-CO-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 16, 'PIF-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 18, 'PIF-AMEND-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 20, 'PIF-EFFECTIVE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 28, 'PIF-EXPIRATION-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 36, 'PIF-INSTALLMENT-TERM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 39, 'PIF-NUMBER-INSTALLMENTS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 41, 'PIF-RISK-STATE-PROV');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 43, 'PIF-COMPANY-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 45, 'PIF-BRANCH');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 47, 'PIF-PROFIT-CENTER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 50, 'PIF-AGENCY-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 57, 'PIF-ENTERED-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 65, 'PIF-TOTAL-AGEN-PREM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 77, 'PIF-LINE-BUSINESS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 80, 'PIF-ISSUE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 81, 'PIF-COMPANY-LINE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 82, 'PIF-PAY-SERVICE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 83, 'PIF-MODE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 84, 'PIF-AUDIT-CODE  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 85, 'PIF-KIND-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 86, 'PIF-VARIATION-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 87, 'PIF-SORT-NAME ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 91, 'PIF-PRODUCER-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 93, 'PIF-REVIEW-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 94, 'PIF-MVR-REPORT-YEAR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 95, 'PIF-RISK-GRADE-GUIDE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 96, 'PIF-RISK-GRADE-UNDWR ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 97, 'PIF-RENEWAL-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 98, 'PIF-REASON-AMENDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 101, 'PIF-RENEW-PAY-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 102, 'PIF-RENEW-MODE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 103, 'PIF-RENEW-POLICY-SYMBOL');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 106, 'PIF-RENEW-POLICY-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 113, 'PIF-ORIGINAL-INCEPT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 119, 'PIF-CUSTOMER-NUMBER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 129, 'PIF-SPECIAL-USE-A ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 133, 'PIF-SPECIAL-USE-B ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 140, 'PIF-ZIP-POSTAL-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 146, 'PIF-ADDRESS-LINE-1 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 176, 'PIF-ADDRESS-LINE-2');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 206, 'PIF-ADDRESS-LINE-3 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 236, 'PIF-ADDRESS-LINE-4  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 266, 'PIF-HISTORY-OPTION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 267, 'PIF-FINAL-AUDIT-IND ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 269, 'PIF-EXCESS-CLAIM-IND  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(1, 270, 'PIF-REST-OF-ZIP-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 0, 'COMMENTS-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 2, 'COMMENTS-REASON-SUSPENDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 4, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 5, 'COMMENTS-DEST ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 10, 'COMMENTS-REQUESTED-BY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 13, 'COMMENTS-SUSPENSE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 21, 'COMMENTS-SEQ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(2, 23, 'COMMENTS-AREA ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 0, 'DESCRIPTION-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 2, 'USE-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 4, 'UNIT-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 7, 'DESCRIPTION-SEQUENCE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 8, 'DESCRIPTION-SORT-NAME');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 12, 'DESCRIPTION-ZIP-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 18, 'DESCRIPTION-LINE-1 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 48, 'DESCRIPTION-LINE-2 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 78, 'DESCRIPTION-LINE-3 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(3, 108, 'DESCRIPTION-LINE-4');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 0, 'FRR-RECORD-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 2, 'FRR-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 4, 'FRR-AMENDMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 5, 'FRR-LAST-CHANGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 13, 'FRR-LOCATION-STATE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 15, 'FRR-TERRITORY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 17, 'FRR-FORM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 18, 'FRR-NUMBER-OF-FAMILIES ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 20, 'FRR-OCCUPANCY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 21, 'FRR-CONSTRUCTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 22, 'FRR-PROTECTION-CLASS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 24, 'FRR-DEDUCTIBLE-TYPE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 25, 'FRR-DEDUCTIBLE-AMOUNT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 29, 'FRR-HYDRANT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 33, 'FRR-FIRE-STATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 34, 'FRR-INSIDE-CITY   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 36, 'FRR-BUILDING-AMOUNT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 43, 'FRR-BUILDING-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 51, 'FRR-CONTENTS-AMOUNT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 58, 'FRR-CONTENTS-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 66, 'FRR-EC-AEC-COVERAGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 67, 'FRR-VANDALISM-MALICIOUS-MIS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 68, 'FRR-NUMBER-OF-STORIES ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 69, 'FRR-INFLATION-GUARD ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 71, 'FRR-VALUE-UP ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 72, 'FRR-MONEY-ENDORSEMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 75, 'FRR-YEAR-OF-CONSTRUCTION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 79, 'FRR-AGENTS-COMMISSION   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 82, 'FRR-ZIP-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 87, 'FRR-ORIGINAL-RATE-BOOK');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 88, 'FRR-COUNTY-TAX-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 91, 'FRR-CITY-TAX-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 94, 'FRR-CURR-REPLACEMENT-COST ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 100, 'FRR-CURR-REPLACE-COST-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 106, 'FRR-REPLACEMENT-COST ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 112, 'FRR-INSPECTION-YEAR  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 116, 'FRR-LAST-VALUE-CHANGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 117, 'FRR-INSPECTION-REPORT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 118, 'FRR-REPLACE-COST-METHOD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 119, 'FRR-HISTORY-OPTION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 120, 'FRR-NEW-PREMIUM   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 129, 'FRR-OLD-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 138, 'FRR-WINDSTORM-ASSUMPTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 139, 'FRR-COMMERCIAL-INDICATOR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 140, 'FRR-RATE-BOOK ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 141, 'FRR-LAST-CHANGE-FACTOR   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 144, 'FRR-PERSONAL-LIABILITY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 145, 'FRR-MEDICAL-PAYMENTS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 146, 'FRR-BODILY-INJURY  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 147, 'FRR-PROPERTY-DAMAGE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 148, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 150, 'XTEND-COVERAGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 151, 'WIND_CONSTRUCT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(4, 152, 'COINS-PCT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 0, 'PCTL-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 2, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 3, 'PCTL-LOC');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 5, 'PCTL-FORM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 12, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 14, 'PCTL-SEQ-01');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 16, 'PCTL-SEQ-02');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 18, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 20, 'PCTL-DATA-01');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 60, 'PCTL-DATA-02');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 100, 'PCTL-DATA-03');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 140, 'PCTL-DATA-04');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(5, 180, 'PCTL-DATA-05');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 0, 'FIRE-PREMIUM-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 2, 'FIRE-PREMIUM-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 3, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 4, 'FIRE-TOTAL-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 13, 'FIRE-PREMIUM-FORMS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 16, 'FIRE-PREMIUM-SEGMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(6, 18, 'FIRE-COVERAGE-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 0, 'HRR-RECORD-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 2, 'HRR-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 3, 'HRR-AMENDMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 4, 'HRR-LAST-CHANGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 12, 'HRR-LOCATION-STATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 14, 'HRR-TERRITORY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 16, 'HRR-FORM  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 17, 'HRR-NUMBER-OF-FAMILIES ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 18, 'HRR-CONSTRUCTION  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 19, 'HRR-PROTECTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 21, 'HRR-DEDUCTIBLE-TYPE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 22, 'HRR-DEDUCTIBLE-AMOUNT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 26, 'HRR-COVERAGE-A-LIMIT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 32, 'HRR-COVERAGE-A-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 40, 'HRR-COVERAGE-B-LIMIT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 45, 'HRR-COVERAGE-C-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 51, 'HRR-COVERAGE-C-PREMIUM ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 59, 'HRR-COVERAGE-D-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 64, 'HRR-COVERAGE-D-PREMIUM  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 72, 'HRR-COVERAGE-E-LIMIT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 79, 'HRR-COVERAGE-F-LIMIT  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 84, 'HRR-COVERAGE-E-F-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 92, 'HRR-APPROVED-ROOF ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 93, 'HRR-HYDRANT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 97, 'HRR-INSIDE-CITY  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 99, 'HRR-AUTOMATIC-VALUE-UP');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 100, 'HRR-NO-OF-APARTMENTS  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 102, 'HRR-LIABILITY-ZONE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 104, 'HRR-MONEY-ENDORSEMENT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 107, 'HRR-FIRE-EC-RATE  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 112, 'HRR-WIND-HAIL-EXCLUSION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 113, 'HRR-THEFT-EXTENSION  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 114, 'HRR-INFLATION-GUARD  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 116, 'HRR-THEFT-250-DEDUCTIBLE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 117, 'HRR-CLASS-RATED ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 118, 'HRR-YEAR-OF-CONSTRUCTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 122, 'HRR-ZIP-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 127, 'HRR-ORIG-ENDRSE-RT-BOOK');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 128, 'HRR-COUNTY-LOCATION  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 131, 'HRR-CITY-LOCATION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 134, 'HRR-CURR-REPLACEMENT-COST');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 137, 'HRR-CONTINGENT-LIABILITY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 138, 'HRR-SPECIAL-LOSS-PCT  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 141, 'HRR-CURR-REPLACE-COST-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 147, 'HRR-REPLACEMENT-COST ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 150, 'SECONDARY-RESIDENCE-USE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 151, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 152, 'HRR-HIGH-ORDER-COVD-DIGIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 153, 'HRR-INSPECTION-YEAR ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 157, 'HRR-LAST-VALUE-CHANGE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 158, 'HRR-INSPECTION-REPORT  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 159, 'HRR-REPLACE-COST-METHOD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 160, 'HRR-AGENT-COMMISSION  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 163, 'HRR-HISTORY-OPTION   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 164, 'HRR-NEW-PREMIUM   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 173, 'HRR-OLD-PREMIUM   ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 182, 'HRR-PREMIUM-GROUP');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 185, 'HRR-ORIGINAL-RATE-BOOK ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(7, 186, 'HRR-LAST-CHANGE-FACTOR ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 0, 'HOMEOWNERS-PREM-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 2, 'HOMEOWNERS-PREM-SEQ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 3, 'Filler');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 4, 'HOMEOWNERS-BASE-PREM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 13, 'HOMEOWNERS-PREM-FORM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 16, 'HOMEOWNERS-PREM-SEG');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(8, 17, 'HOMEOWNERS-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 0, 'DRIVER-KEY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 2, 'DRIVER-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 4, 'DRIVER-NAME');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 26, 'DRIVER-LICENSE-NBR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 45, 'DRIVER-DATE-BIRTH');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 53, 'DRIVER-LICENSE-STATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 55, 'DRIVER-SEX');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 56, 'DRIVER-MARITAL-STAT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 57, 'DRIVER-RLTN-TO-INDS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 58, 'DRIVER-PRIN-OPRTR (1)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 59, 'DRIVER-PRIN-OPRTR (2)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 60, 'DRIVER-PRIN-OPRTR (3)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 61, ' DRIVER-PT-OPRTR (1)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 62, ' DRIVER-PT-OPRTR (2)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 63, ' DRIVER-PT-OPRTR (3)');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 64, 'DRIVER-AGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 66, 'DRIVER-SPECIAL-USE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 72, 'DRIVER-CF-ATTRIBUTE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 73, 'ATTRIBUTE-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 76, 'ATTRIBUTE-VALUE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(9, 77, 'ATTRIBUTE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 0, 'PER-ID ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 2, 'PER-USE-CD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 3, 'PER-USE-DATA');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 6, 'PER-USE-SEQUENCE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 7, 'PER-AMENDMENT-NBR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 8, 'PER-ENTERED-DATE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 16, 'PER-DESC-LINE-1');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 96, 'PER-DESC-LINE-2 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 166, 'PER-DESC-LINE-3 ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 226, 'HISTORY-STATUS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 227, 'ORIGINAL-RATEBOOK');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(10, 228, 'CURRENT-RATEBOOK');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 0, 'VCR-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 2, 'VCR-UNIT-NUMBER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 5, 'VCR-SEGMENT-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 6, 'VCR-AMEND-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 7, 'VCR-CHANGE-EFFECT-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 15, 'VEHICLE-REASON-AMENDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 18, 'VEHICLE-TOTAL-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 27, 'VEHICLE-OLD-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 36, 'VCR-COVERAGE-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 38, 'VCR-COVERAGE-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 45, 'VCR-COVERAGE-PREMIUM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(11, 54, 'VCR-CVRG-RATE-BOOK-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 0, 'FORMS-ID ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 2, 'FORMS-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 5, 'FORM-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 12, 'FORM-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(12, 16, 'FORM-ACTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 0, 'REIN-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 2, 'REINS-SECTION-CODE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 3, 'REINS-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 6, 'REINS-LAYER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 7, 'REINS-COMPANY-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 11, 'REINS-EFFECTIVE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 19, 'REINS-PCT-PREM-CEDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 26, 'REINS-PCT-LOSS-CEDED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 33, 'REINS-PCT-FAC-COMM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 38, 'REINS-EXPRTION-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 46, 'REINS-CESSION-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 56, 'REINS-TYPE  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 57, 'REINS-ENTERED-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 65, 'REINS-BROKER-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 69, 'REINS-EXCESS-AMT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 78, 'REINS-OCCUR-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 87, 'REINS-AGGR-LIMIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(13, 96, 'REINS-SPECIAL-USE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 0, 'LOSS-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 2, 'LOSS-UNIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 5, 'LOSS-MAJOR-PERIL');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 8, 'LOSS-MAJOR-PERIL-SEQ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 10, 'LOSS-COV-EFF-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 18, 'LOSS-PART    ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 19, 'LOSS-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 27, 'LOSS-OCCURENCE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 29, 'LOSS-CLAIMANT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 31, 'LOSS-TRANSACTION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 33, 'LOSS-REINS-CO-NO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 37, 'LOSS-DATE-REPORTED');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 45, 'LOSS-CAUSE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 47, 'LOSS-CATASTROPHE-NO ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 49, 'LOSS-XCSS-CATASTROPHE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 54, 'LOSS-ADJUSTOR-NO ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 57, 'LOSS-EXAMINER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 59, 'LOSS-PAID-OR-RESV-AMT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 70, 'LOSS-EXPENSE-AMT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 79, 'LOSS-BANK-NUMBER');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 81, 'LOSS-DRAFT-NO ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 86, 'LOSS-DATE-OF-DRAFT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 94, 'LOSS-DRAFT-PAY-TO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 97, 'LOSS-DRAFT-MAIL-TO');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 98, 'LOSS-ORIGINAL-RESERVE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 106, 'LOSS-ACCT-ENTERED-DT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 112, 'LOSS-CLAIMANT-NAME');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 142, 'LOSS-PLANT-LOCATION');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 146, 'LOSS-ACCIDENT-STATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 148, 'LOSS-AVG-RESERVE-CD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 149, 'LOSS-BRANCH');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 152, 'LOSS-IND-DRAFT-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 160, 'LOSS-WEEKLY-WAGE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 166, 'LOSS-PAYMENT-RATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 172, 'LOSS-FREQUENCY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 173, 'LOSS-PERIOD-PAY');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 176, 'LOSS-CYCLE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 177, 'LOSS-AGE  ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 179, 'LOSS-TIME-EMP-YEARS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 181, 'LOSS-TIME-EMP-MTHS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 183, 'LOSS-DISABILITY ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 185, 'LOSS-INDUSTRIAL-COMM');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 195, 'LOSS-CESSION ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 205, 'LOSS-AIA-CODES');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 211, 'LOSS-ACCIDENT-DESC');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 241, 'LOSS-NET-CHG-OFFSET');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 245, 'LOSS-NEXT-REVIEW-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 253, 'LOSS-1099-NUMBER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 263, 'LOSS-CLAIM-PAYEE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 266, 'LOSS-NOTES-DRFT-PAYEE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 284, 'LOSS-CONVERSION-NBR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 296, 'LOSS-SPECIAL-USE-1');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 304, 'LOSS-SPECIAL-USE-2');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 307, 'LOSS-SUIT ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 308, 'LOSS-EXCESS-STATUS-IND');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 309, 'LOSS-TIME');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(14, 313, 'LOSS-DAY-NR');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 0, 'ARR-ID');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 2, 'ARR-BASE-BILLING-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 10, 'ARR-DUE-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 18, 'ARR-ACCT-TRANS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 20, 'ARR-RCPT-TRANS');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 22, 'ARR-AMT-DUE-RCVD');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 33, 'ARR-NOTICE-CODE ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 34, 'ARR-DATE-LAST-NOTICE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 42, 'ARR-CARRY-DATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 50, 'ARR-DATE-OF-DEPOSIT');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 58, 'ARR-RCPT-COMM-RATE');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 61, 'ARR-BANK-NUMBER ');
INSERT INTO COLUMN_INFO(segment_id,start_index,column_name_) VALUES(15, 63, 'ARR-PRIOR-AMT-BILL');
